

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3

      - name: Login to Docker
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
