

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     

      - name: Testing
        run: pwd

      - name: Printbefore
        run: echo Rahomah
        run: ls -a

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: PrintAfter
        run: echo Rahomah
        run: ls -a